// MEMBER PAGES
export const GET_MEMBER_ACCOUNT = 'GET_MEMBER_ACCOUNT'
export const GET_MEMBER_PROFILE = 'GET_MEMBER_PROFILE'
export const GET_MEMBER_ROLE = 'GET_MEMBER_ROLE'
export const GET_MEMBER_TOTAL = 'GET_MEMBER_TOTAL'
export const GET_MEMBER_START = 'GET_MEMBER_START'
export const GET_MEMBER_END = 'GET_MEMBER_END'

// PARKING AREA PAGES
export const GET_PARKING_AREA = 'GET_PARKING_AREA'
export const GET_PARKING_START = 'GET_PARKING_START'
export const GET_PARKING_END = 'GET_PARKING_END'
export const PARKING_UPLOAD = 'PARKING_UPLOAD'

// RATING PAGE
export const GET_RATING = 'GET_RATING'
export const GET_RATING_TOTAL = 'GET_RATING_TOTAL'
export const GET_RATING_START = 'GET_RATING_START'
export const GET_RATING_END = 'GET_RATING_END'

// HISTORY PAGE
export const GET_HISTORY = 'GET_HISTORY'
export const GET_HISTORY_ACTIVE = 'GET_HISTORY_ACTIVE'
export const GET_HISTORY_TOTAL = 'GET_HISTORY_TOTAL'
export const GET_HISTORY_ACTIVE_TOTAL = 'GET_HISTORY_ACTIVE_TOTAL'
export const GET_HISTORY_START = 'GET_HISTORY_START'
export const GET_HISTORY_END = 'GET_HISTORY_END'

// PAYMENT PAGE
export const GET_PAYMENT = 'GET_PAYMENT'
export const GET_PAYMENT_TOTAL = 'GET_PAYMENT_TOTAL'
export const GET_PAYMENT_TYPE = 'GET_PAYMENT_TYPE'
export const GET_PAYMENT_STATUS = 'GET_PAYMENT_STATUS'
export const GET_PAYMENT_START = 'GET_PAYMENT_START'
export const GET_PAYMENT_END = 'GET_PAYMENT_END'

// VEHICLE PAGE
export const GET_CAR_BRAND = 'GET_CAR_BRAND'
export const GET_CAR_BRAND_TOTAL = 'GET_CAR_BRAND_TOTAL'
export const GET_CAR_TYPE = 'GET_CAR_TYPE'
export const GET_CAR_TYPE_TOTAL = 'GET_CAR_TYPE_TOTAL'
export const GET_MOTOR_BRAND = 'GET_MOTOR_BRAND'
export const GET_MOTOR_BRAND_TOTAL = 'GET_MOTOR_BRAND_TOTAL'
export const GET_MOTOR_TYPE = 'GET_MOTOR_TYPE'
export const GET_MOTOR_TYPE_TOTAL = 'GET_MOTOR_TYPE_TOTAL'
export const GET_ALL_BRANDS = 'GET_ALL_BRANDS'
export const GET_VEHICLE_START = 'GET_VEHICLE_START'
export const GET_VEHICLE_END = 'GET_VEHICLE_END'

// PARTNER PAGE
export const GET_PARTNER = 'GET_PARTNER'
export const GET_PARTNER_START = 'GET_PARTNER_START'
export const GET_PARTNER_END = 'GET_PARTNER_END'

// USER : LOGIN AND LOG_OUT
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const STAY_LOG_IN = 'STAY_LOG_IN'
export const ERROR_LOG_IN = 'ERROR_LOG_IN'
export const CLEAR_ERROR_LOG_IN = 'CLEAR_ERROR_LOG_IN'

// COMPANY PROFILE
export const GET_COMPANY = 'GET_COMPANY'
export const GET_COMPANY_START = 'GET_COMPANY_START'
export const GET_COMPANY_END = 'GET_COMPANY_END'

// COMPONENTS
export const BURGER = 'BURGER'
export const AVATAR = 'AVATAR'
export const BURGER_PATH = 'BURGER_PATH'
