// MEMBER PAGES
export const GET_MEMBER_ACCOUNT = 'GET_MEMBER_ACCOUNT'
export const GET_MEMBER_PROFILE = 'GET_MEMBER_PROFILE'
export const GET_MEMBER_ROLE = 'GET_MEMBER_ROLE'
export const GET_MEMBER_TOTAL = 'GET_MEMBER_TOTAL'
export const GET_MEMBER_START = 'GET_MEMBER_START'
export const GET_MEMBER_END = 'GET_MEMBER_END'

// PARKING AREA PAGES
export const GET_PARKING_AREA = 'GET_PARKING_AREA'
export const GET_PARKING_START = 'GET_PARKING_START'
export const GET_PARKING_END = 'GET_PARKING_END'
export const PARKING_UPLOAD = 'PARKING_UPLOAD'