// user authentication --> user CRUD purpose
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR'
export const REGISTER = 'REGISTER'

// user account
export const GET_USER_ACCOUNT = 'GET_USER_ACCOUNT'
export const GET_USER_ACCOUNT_ERROR = 'GET_USER_ACCOUNT_ERROR'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR'
export const GET_COMPANY_PROFILE = 'GET_COMPANY_PROFILE'

// DOM action => action toogle from DOM interactions
export const BURGER = 'BURGER'
export const AVATAR = 'AVATAR'
export const BURGER_PATH = 'BURGER_PATH'

// stay login
export const STAY_LOGIN = 'STAY_LOG_IN'

// DATA SETS
export const TOTAL_USER = 'TOTAL_USER'
// export const TOTAL_VEHICLE = 'TOTAL_VEHICLE'
export const TOTAL_RATING = 'TOTAL_RATING'
export const TOTAL_HISTORY = 'TOTAL_HISTORY'
export const GET_ROLES = 'GET_ROLES'

// data sets : USER Accounts and Profiles
export const GET_USER = 'GET_USER'
export const GET_USER_START = 'GET_USER_START'
export const GET_USER_END = 'GET_USER_END'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_START = 'GET_PROFILE_START'
export const GET_PROFILE_END = 'GET_PROFILE_END'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'

// data sets : VEHICLE
export const GET_TOTAL_CAR_BRAND = 'GET_TOTAL_CAR_BRAND'
export const GET_CAR_BRANDS = 'GET_CAR_BRANDS'
export const GET_CAR_BRANDS_ALL = 'GET_CAR_BRANDS_ALL'

export const GET_TOTAL_CAR_TYPE = 'GET_TOTAL_CAR_TYPE'
export const GET_CAR_TYPES = 'GET_CAR_TYPES'

export const GET_TOTAL_MOTOR_BRANDS = 'GET_TOTAL_MOTOR_BRANDS'
export const GET_MOTOR_BRANDS = 'GET_MOTOR_BRANDS'
export const GET_MOTOR_BRANDS_ALL = 'GET_MOTOR_BRANDS_ALL'

export const GET_TOTAL_MOTOR_TYPES = 'GET_TOTAL_MOTOR_TYPES'
export const GET_MOTOR_TYPES = 'GET_MOTOR_TYPES'

// data sets : RATING
export const GET_RATING_TOTAL = 'GET_RATING_TOTAL'
export const GET_RATING = 'GET_RATING'

// data sets : HISTORY
export const GET_HISTORY_TOTAL = 'GET_HISTORY_TOTAL'
export const GET_HISTORY = 'GET_HISTORY'
export const GET_ON_ACTIVE_TOTAL = 'GET_ON_ACTIVE_TOTAL'
export const GET_ON_ACTIVE = 'GET_ON_ACTIVE'

// data sets : PAYMENT
export const GET_TRANSACTION_HISTORY_TOTAL = 'GET_TRANSACTION_HISTORY_TOTAL'
export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY'
export const GET_TRANSACTION_HISTORY_STATUS = 'GET_TRANSACTION_HISTORY_STATUS'
export const GET_TRANSACTION_HISTORY_TYPE = 'GET_TRANSACTION_HISTORY_TYPE'
export const TRANSACTION_PROCESS_START = 'TRANSACTION_PROCESS_START'
export const TRANSACTION_PROCESS_END = 'TRANSACTION_PROCESS_END'

// data sets : PARKING AREA
export const GET_PARKING_AREA = 'GET_PARKING_AREA'
export const PARKING_START = 'PARKING_START'
export const PARKING_PROCCESS = 'PARKING_PROCCESS'
export const PARKING_END = 'PARKING_END'

// data sets : PARTNERS
export const GET_PARTNERS = 'GET_PARTNERS'

// data sets : COMPANY
export const GET_COMPANY = 'GET_COMPANY'