export const API_URL = 'http://localhost:5000'
export const API_URL_ADMIN = 'http://localhost:5000/api/admin'
export const API_URL_USER = 'http://localhost:5000/api/user'
export const API_RATING = 'http://localhost:5000/api/rating'
export const API_HISTORY = 'http://localhost:5000/api/history'
export const API_PAYMENT = 'http://localhost:5000/api/payment'
export const API_PARKING = 'http://localhost:5000/api/parking'
export const API_PARTNER = 'http://localhost:5000/api/partner'